version: '3.8'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/meetingbot
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
